---
title: "Population Genomics Workshop: Identification of Imported Cases"
author: "Kirsty McCann"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: false
---

::: callout-important
## DISCLAIMER

The following tutorial is simulated for workshops purposes.

This workshop should only be used for training purposes.
:::

# The Scenario

In early 2025, an unexpected cluster of approximately 200 *Plasmodium falciparum* malaria cases was reported in a district of Namibia that had previously achieved malaria-free status in 2019. As a major tourism destination, the district receives travellers from across Africa, Europe, and Asia. With malaria elimination dependent on preventing re-establishment, every unusual case raises the possibility of importation.

Although Namibia has achieved very low local transmission, neighbouring countries, particularly Angola, continue to experience substantial malaria burden. The region has a long history of cross-border movement, particularly with workers travelling and occasional parasite importation, making it challenging to immediately determine where a new outbreak is coming from. It is not clear whether we receive the correct travel movements of all those reporting malaria symptoms.

To investigate the origin of this cluster, all cases were genotyped using a global 180-SNP barcode panel. This compact marker set captures key neutral variations across the *P. falciparum* genome and allows rapid inference of:

-   population structure

-   genetic relatedness

-   direction of parasite movement

-   transmission clustering

:::: callout-important
::: {style="green"}
## Question
:::

#### Can you you identify where in the world the outbreak has originated?
::::
