---
title: "Mapping Sampling Locations"
editor: visual
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: false
---

```{r load-packages, include=FALSE}
library(vcfR)
library(adegenet)
library(poppr)
library(ape)
library(pegas)
library(ggplot2)
library(dplyr)
library(reshape2)
library(ggtree)
library(viridis)
library(dartR.base)
library(hierfstat)
library(tidyr)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(scales)

meta <- read.table("data/metadata_samples.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

```

## 9. Mapping Sampling Locations

::: callout-note
### Exercises for Section 9. Mapping Sampling Locations

-   Plot where all the samples are collected from?
-   Can you change the shape of SEA samples vs AFR samples?
:::

```{r map-sampling, echo=TRUE, message=FALSE, warning=FALSE, paged.print=FALSE}
# Ensure country is a proper factor with no empty strings
meta$country[meta$country == "" | is.na(meta$country)] <- "Unknown"

# Remove any samples missing coordinates
meta <- meta %>% filter(!is.na(latitude), !is.na(longitude))

meta_sf <- st_as_sf(meta,
                    coords = c("longitude", "latitude"),
                    crs = 4326,
                    remove = FALSE)   # keep original columns


# Load world map
world <- ne_countries(scale = "medium", returnclass = "sf")
saveRDS(world, file = "derived/world.rds")

map <- ggplot() +
  geom_sf(data = world, fill = "grey90", color = "grey60", linewidth = 0.2) +
  geom_sf(data = meta_sf,
          aes(color = country),
          size = 2, alpha = 0.8) +
  coord_sf(xlim = c(-20, 120), ylim = c(-25, 25), expand = FALSE) +
  scale_color_viridis_d() +
  theme_minimal() +
  labs(title = "Sampling Locations of P. falciparum Isolates",
       x = "Longitude", y = "Latitude")

```

::: {.callout-note collapse="true"}
## Click to see plot

```{r}
#| echo: false
map
```
:::
