---
title: "Setup"
editor: visual
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

## 1. Install and Load Packages and Data

To install the following packages on your computer you will need to use: install.packages() or if (!require("BiocManager", quietly = TRUE)) install.packages("BiocManager") BiocManager::install()

Note: The \#'s throughout the file are comments, if you remove the \# from the line in the code chunk you can run that line.

```{r load-packages}
#(!require("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
#BiocManager::install()

#install.packages("vcfR")
library(vcfR)
library(adegenet)
library(poppr)
library(ape)
library(pegas)
library(ggplot2)
library(dplyr)
library(reshape2)
library(ggtree)
library(viridis)
library(dartR.base)
library(hierfstat)
library(tidyr)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(scales)


```

```{r load_files}

# Extended metadata with sites, coordinates, and DR mutations
meta <- read.table("metadata_samples_extended.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

# load the African data and the Southeast Asia data. You will need both of these to find where the imported cases are.
AFR <- read.vcfR("AFR_180snp_DR.vcf")
SEA <- read.vcfR("SEA_180snp_DR.vcf")

AFR
SEA
```
